[package]
name = "rust-synapse-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "*"
url = "*"
# tokio = {version = "*", features = ["full"]}